### ISSUE TITLE
[AnVIL Portal] Implement CSER consortia pages

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#2542]
- [ ] https://github.com/anvilproject/anvil-portal/issues/2109
https://drive.google.com/drive/folders/1Wkg6noL3AZoZDExxg54fSb5GY0jLC5UC?usp=sharing_eil_m&ts=63dd47e6

Please look at the JSON file for the current site structure and how this lists on the site. 

Target earlier rather than later in Q2.

Let's break this down into sub-tasks. We may not do all of the scopes in the mocks in the first round.
The main goal is to get the PDFs listed where they can be found.

See [mocks](https://www.figma.com/proto/i4uZsYkKAML9ivi2TIo6ug/HCA-Data-Explorer?page-id=2529%3A26617&node-id=2529-27637&viewport=1782%2C874%2C0.54&scaling=min-zoom&starting-point-node-id=2529%3A26618&hide-ui=1).

```[tasklist]
### Tasks
- [ ] https://github.com/anvilproject/anvil-portal/issues/2693
- [ ] https://github.com/clevercanary/anvil-portal/issues/4
- [ ] https://github.com/clevercanary/findable-tf/issues/16
- [ ] https://github.com/clevercanary/findable-tf/issues/17
- [ ] https://github.com/clevercanary/altos-data-browser/issues/59
- [ ] https://github.com/anvilproject/anvil-portal/issues/2677
- [ ] https://github.com/anvilproject/anvil-portal/issues/2692
- [ ] https://github.com/DataBiosphere/data-browser/issues/3379
- [ ] https://github.com/anvilproject/anvil-portal/issues/2678
- [ ] https://github.com/DataBiosphere/findable-ui/issues/6
- [ ] https://github.com/DataBiosphere/findable-ui/issues/7
- [ ] https://github.com/DataBiosphere/findable-ui/issues/8
- [ ] https://github.com/anvilproject/anvil-portal/issues/2679
- [ ] https://github.com/DataBiosphere/findable-ui/issues/9
- [ ] https://github.com/anvilproject/anvil-portal/issues/2680
- [ ] https://github.com/anvilproject/anvil-portal/issues/2682
- [ ] https://github.com/anvilproject/anvil-portal/issues/2683
- [ ] https://github.com/anvilproject/anvil-portal/issues/2681
- [ ] https://github.com/anvilproject/anvil-portal/issues/2684
- [ ] https://github.com/anvilproject/anvil-portal/issues/2685
- [ ] https://github.com/anvilproject/anvil-portal/issues/2686
- [ ] https://github.com/anvilproject/anvil-portal/issues/2687
- [ ] https://github.com/anvilproject/anvil-portal/issues/2688
- [ ] https://github.com/anvilproject/anvil-portal/issues/2689
```

```[tasklist]
### Version Awesome
- [ ] https://github.com/clevercanary/data-explorer/issues/197
- [ ] https://github.com/anvilproject/anvil-portal/issues/2690
- [ ] https://github.com/anvilproject/anvil-portal/issues/2691
- [ ] https://github.com/DataBiosphere/data-browser/issues/3383
```

```[tasklist]
### UI Tasks
- [ ] https://github.com/clevercanary/cc-design/issues/40
- [ ] https://github.com/clevercanary/cc-design/issues/41
- [x] [Button to consortia from AnVIL catalog](https://www.figma.com/proto/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=3804-34301&scaling=min-zoom&page-id=1008%3A14844&starting-point-node-id=1047%3A16475).
- [ ] https://github.com/clevercanary/cc-design/issues/42
```

```[tasklist]
### Questions
- [ ] Scope - is news in scope?
```
