### ISSUE TITLE
2023 Q1 - Monthly analytics reports

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#2621]
```[tasklist]
### Tasks
- [ ] https://github.com/anvilproject/anvil-portal/issues/2501
- [ ] https://github.com/anvilproject/anvil-portal/issues/2599
- [ ] https://github.com/anvilproject/anvil-portal/issues/2628
```
