### ISSUE TITLE
[AnVIL Portal] Migrate Portal to Nextjs/findable-ui 

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [anvilproject/anvil-portal#2670]
```[tasklist]
### Tasks
- [ ] https://github.com/clevercanary/anvil-portal/issues/4
- [ ] https://github.com/clevercanary/findable-tf/issues/16
- [ ] https://github.com/clevercanary/findable-tf/issues/17
```

**Comment by MillenniumFalconMechanic** [comment]
Dupe.
